version: "3.9"
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=frances
      - POSTGRES_PASSWORD=frances
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  fuseki:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=pass123
      - JVM_ARGS=-Xmx4g
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: 10gb
